<h1>Mentions légales</h1>
<h2 class="title-with-underline" style="text-align: center; margin-bottom: 60px;">Mentions <span class="highlight">Légales</span></h2>
<div style="margin: 20px 130px;">
    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor finibus sodales. Etiam viverra eu diam non vulputate. Suspendisse risus augue, consectetur facilisis egestas vitae, feugiat commodo dolor. Nunc efficitur convallis eros venenatis mollis. Aliquam erat volutpat. Morbi congue egestas nibh, non lobortis magna condimentum scelerisque. Nunc sodales orci ut vehicula dapibus. Nulla rutrum nisl velit, eget eleifend libero pulvinar et. Integer ultricies dolor sit amet scelerisque semper. Fusce pharetra pulvinar vehicula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce arcu quam, tempor non venenatis convallis, semper id dui. Maecenas euismod, tellus at varius ultricies, velit lectus consequat mi, sed sagittis sem erat non nisl.<br>

Donec vestibulum magna vel neque iaculis euismod. Phasellus lectus augue, porttitor sit amet interdum ac, placerat a purus. Nam auctor sapien sit amet sagittis fermentum. Vivamus condimentum purus mi, non sagittis ipsum commodo in. Proin vitae elit nec nisi consectetur pretium ac ut metus. Pellentesque dui urna, fermentum sit amet erat eget, ornare aliquet enim. Duis ornare libero dui, ultrices tincidunt augue posuere eget. Ut a tellus interdum leo vestibulum convallis quis ac dolor. Aenean sodales sed nisi fermentum mattis. Cras egestas malesuada ullamcorper. Ut ullamcorper commodo ante nec porttitor. Suspendisse imperdiet urna at arcu vestibulum, vitae cursus libero pulvinar.<br>

Suspendisse ac risus eu ex iaculis gravida sed semper neque. Sed luctus lorem imperdiet orci scelerisque, non posuere leo mattis. Pellentesque quis tellus eget metus consectetur viverra ac nec massa. Nunc sodales condimentum mi sit amet faucibus. Etiam elementum, justo vitae gravida ornare, tortor turpis euismod dolor, euismod pretium massa ipsum ac leo. Quisque efficitur, neque scelerisque lobortis placerat, risus leo rutrum enim, at gravida lectus lectus vitae massa. Sed laoreet consequat tellus, a lacinia odio euismod vitae. Sed viverra finibus luctus. Proin pretium odio sit amet condimentum accumsan. Sed pellentesque consectetur vestibulum.<br>

Integer molestie varius elit non interdum. Nulla varius eu elit non pretium. Etiam eleifend blandit nisl quis lacinia. Nam laoreet id dui in vulputate. Suspendisse iaculis ligula semper, dictum mauris sit amet, viverra urna. Pellentesque auctor nisi ac purus maximus, et bibendum dui finibus. Aliquam sem dui, vestibulum vel lacus id, vehicula accumsan eros. Quisque dolor turpis, efficitur ut dolor vitae, varius consectetur quam. Donec in quam sit amet est iaculis rhoncus vel non magna. Nam cursus blandit pharetra. Phasellus quis lacus scelerisque, porttitor sapien quis, pulvinar sem. Nulla suscipit, felis vel tincidunt fermentum, elit nulla sodales nisl, ac varius dui nunc eu ipsum. In sed auctor turpis. Ut placerat nunc justo, at semper est feugiat in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse in aliquam felis.<br>

Fusce a luctus mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce venenatis vel risus lobortis laoreet. Aliquam mattis commodo tortor accumsan placerat. Duis condimentum metus augue, eget viverra est malesuada non. Suspendisse rutrum nibh ipsum, id elementum libero sagittis et. Proin rutrum porttitor quam, eget sollicitudin magna. Integer blandit velit nec purus fermentum, sit amet posuere nisl iaculis. Suspendisse finibus tincidunt auctor. Phasellus tempor, odio nec faucibus imperdiet, mauris sapien rhoncus elit, quis varius nisl ex at nulla. Integer et dui magna. </p>
    </div>
